### ISSUE TITLE
About the topics

### ISSUE THREAD

**Issue by zhengnx0906** [TAIL-Robot/TAIL-dataset#2]
您好，您在网站上说rosbag里面包含了机构的运动信息“Specially, tail provide the sensor data from wheel(wheel odom, vel, motor rpm and current) and quadruped robots(leg odom, contact and motor status).”我在rosbag并没有看到。
![屏幕截图 2024-05-31 20:03:41](https://github.com/TAIL-Robot/TAIL-dataset/assets/55745484/8a7bd203-ab17-4798-aeb2-57550b571983)
还有您能提供下benchmark的测试轨迹吗？万分感激。

**Comment by crankler** [comment]
Thank you for testing our dataset. We have inspected the odometry data from both wheeled and quadruped robots and have found that the wheeled robot's data is ok. Have you had the time to test it as well? 
Furtheremore, we have discovered that we omitted the quadruped odometry information during data compression. We are currently working on processing and uploading them now.

**Comment by wsjpla** [comment]
您好，修复后roabag已经重新上传了，可以重新下载了

The fixed rosbags have already been re-uploaded, and they can be downloaded now.

**Comment by zhengnx0906** [comment]
还有一个小问题，请问你们如何标定机身中心与其他传感器的位置，我现在手上有一台机器人，想要知道这个

**Comment by zhengnx0906** [comment]
还有一个小问题，请问你们如何标定机身中心与其他传感器的位置，我现在手上有一台机器人，想要知道这个自己做个标定

**Comment by crankler** [comment]
We get the calibration data towards robot baselink from CAD,  please check our paper and dataset.
